sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - "10"

script:
  - cd site
  - yarn
  - yarn test
  - yarn build

deploy:
  provider: pages
  local-dir: site/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
