sudo: false
language: node_js
cache:
  - yarn
  directories:
    - scripts/tmp
notifications:
  email: false
node_js:
  - "10"

script:
  - cd scripts
  - yarn
  - node analyzeSource.js
  - cd ../site
  - yarn
  - yarn test
  - yarn build

deploy:
  provider: pages
  local-dir: site/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
