sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - "10"

script:
  - cd site && yarn
  - ls -al
  - cd site && yarn build
after_success:
  - cd site && yarn deploy

branches:
  only:
    - master
